### ISSUE TITLE
A gem não funciona no Rails versão 5.2

### ISSUE THREAD

**Issue by diegorv** [BoletoSimples/boletosimples-ruby#9]
Olá,

Acabei de testar a *gem* de vocês em um projeto com `Rails 5.2` e não está funcionando, aparentemente é um problenma relacionado ao `Her`, tem um PR aberto lá por isso: https://github.com/remiprev/her/pull/492, será necessário fazer um update da gem de vocês pra utilizar a versão nova do `Her`, quando ela sair.

Uma amostra do output:

```bash
  68) BoletoSimples::Discharge all
      Failure/Error: it { expect(subject.first).to be_a_kind_of(BoletoSimples::Discharge) }

      NoMethodError:
        undefined method `changed?' for nil:NilClass
      # ./spec/boletosimples/resources/discharge_spec.rb:15:in `block (3 levels) in <top (required)>'

  69) BoletoSimples::Transaction all
      Failure/Error: it { expect(subject.first).to be_a_kind_of(BoletoSimples::Transaction) }

      NoMethodError:
        undefined method `changed?' for nil:NilClass
      # ./spec/boletosimples/resources/transactions_spec.rb:15:in `block (3 levels) in <top (required)>'

  70) BoletoSimples::Remittance all
      Failure/Error: it { expect(subject.first).to be_a_kind_of(BoletoSimples::Remittance) }

      NoMethodError:
        undefined method `changed?' for nil:NilClass
      # ./spec/boletosimples/resources/remittance_spec.rb:15:in `block (3 levels) in <top (required)>'
```

**Comment by eduardofiorezi** [comment]
Mesmo problema aqui também:

```
  1) BankBillet#create error 
     Failure/Error: BoletoSimples::BankBillet.create(attributes)
     
     NoMethodError:
       undefined method `changed?' for nil:NilClass
     # ./app/services/bank_billet.rb:8:in `create'
     # ./spec/services/bank_billet_spec.rb:41:in `block (4 levels) in <top (required)>'
     # ./spec/services/bank_billet_spec.rb:43:in `block (4 levels) in <top (required)>'

  2) BankBillet#create error 
     Failure/Error: BoletoSimples::BankBillet.create(attributes)
     
     NoMethodError:
       undefined method `changed?' for nil:NilClass
     # ./app/services/bank_billet.rb:8:in `create'
     # ./spec/services/bank_billet_spec.rb:41:in `block (4 levels) in <top (required)>'
     # ./spec/services/bank_billet_spec.rb:45:in `block (4 levels) in <top (required)>'

  3) BankBillet#create success 
     Failure/Error: BoletoSimples::BankBillet.create(attributes)
     
     NoMethodError:
       undefined method `changed?' for nil:NilClass
     # ./app/services/bank_billet.rb:8:in `create'
     # ./spec/services/bank_billet_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/services/bank_billet_spec.rb:35:in `block (4 levels) in <top (required)>'

  4) BankBillet#create success 
     Failure/Error: BoletoSimples::BankBillet.create(attributes)
     
     NoMethodError:
       undefined method `changed?' for nil:NilClass
     # ./app/services/bank_billet.rb:8:in `create'
     # ./spec/services/bank_billet_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/services/bank_billet_spec.rb:34:in `block (4 levels) in <top (required)>'
```
